# Shiny with Plotly

<br>

#### **Research Question: How does U.S. math performance compare to other countries in the context of key development indicators?**

<br>

### Data Description

Gapminder dataset
<br>

- **Math achievement**: The average score on the international TIMSS test for children in 4th and 8th grade. 

- **Life expectancy**: The number of years a newborn infant would live if the current mortality rates at different ages were to stay the same throughout its life.

- **Average Income**: Inflation and price adjusted average daily income per person per day. It was calculated using the mean daily household per capita income or consumption expenditure from the world bank survey and is expressed in 2021 constant international dollars (PPP).

- **Expenditure per Student**: The average general government expenditure (current, capital, and transfers) per student in primary school. It is expressed as a percentage of GDP per capita.

- **Country**: Only countries with math achievement data for both 4th and 8th grade were included.

<br>

### Dashboard 

<iframe src="https://daniarachelcarr.shinyapps.io/timss-dashboard/" style="border: 1px solid #AAA; width: 1000px; height: 900px"></iframe>

<br>

### Insights

Overall, between 2000 and 2016, mathematics achievement among 4th-grade students in the United States was higher than among 8th-grade students. In addition, 4th-grade achievement was not improving at the same rate as 8th-grade achievement. In fact, there were no gains in 4th-grade mathematics performance between 2011 and 2015. It is important to note that the data used in this dashboard extend only through 2016, prior to the COVID-19 pandemic, which significantly disrupted schooling and negatively affected mathematics learning in the United States. However, these earlier trends suggest that math performance may have already been stagnating before the pandemic, indicating that factors beyond COVID-19 may be contributing to declining mathematics outcomes.

During this same period, the United States performed better in mathematics than some countries but worse than others. Notably, countries such as Japan and Singapore consistently outperformed the United States in mathematics at both the 4th- and 8th-grade levels. These countries also have higher life expectancy, suggesting that broader indicators of population health and quality of life may be associated with stronger educational outcomes.



